"""
Codex Adapter

Integrates llm-memory with Codex by:
1. Adding project-level AGENTS.md workflow instructions.
2. Installing a marked MCP server block in the Codex config.
"""

from pathlib import Path
from typing import Dict

from llm_memory.hooks.generic import GenericAdapter

CODEX_MARKER = "LLM-MEMORY CODEX MCP"
AGENTS_MARKER = "<!-- LLM-MEMORY-CODEX -->"


class CodexAdapter(GenericAdapter):
    """Adapter for Codex memory workflow integration."""

    def __init__(
        self,
        memory,
        project_root: Path = None,
        config_path: Path = None,
        server_url: str = "http://127.0.0.1:8000",
        repo_id: str = None,
        dry_run: bool = False,
    ):
        super().__init__(
            memory=memory,
            project_root=project_root,
            context_file="AGENTS.md",
            injection_marker=AGENTS_MARKER,
            append_mode=True,
        )
        self.config_path = Path(config_path or Path.home() / ".codex" / "config.toml")
        self.server_url = server_url
        self.repo_id = repo_id or getattr(memory.config, "repo_id", None) or self.project_root.name
        self.dry_run = dry_run

    def install(self) -> Dict[str, bool]:
        """Install project instructions and a Codex MCP config block."""
        results = {}
        results["agents_instructions"] = self._install_agents_instructions()
        results["codex_mcp_config"] = self._install_codex_config()
        return results

    def uninstall(self) -> Dict[str, bool]:
        """Remove only llm-memory managed Codex integration blocks."""
        results = {}
        results["agents_instructions"] = self._remove_agents_instructions()
        results["codex_mcp_config"] = self._remove_codex_config()
        return results

    def update_context(self, files: list[str] = None, task: str = None) -> bool:
        """Refresh the generated memory context inside AGENTS.md."""
        if not self.context_file.exists():
            self.install()

        context = self.get_memory_context(files=files, task=task)
        generated = f"""{self._workflow_instructions()}

## LLM Memory Context

Auto-generated by `llm-memory hooks update codex`.

{context}
"""
        return self._replace_agents_block(generated)

    def get_context_file_path(self) -> Path:
        """Get the Codex project instruction path."""
        return self.context_file

    def config_block(self) -> str:
        """Render the managed Codex MCP config block."""
        env_items = {
            "LLM_MEMORY_STORAGE_MODE": "client",
            "LLM_MEMORY_STORAGE_SERVER_URL": self.server_url,
            "LLM_MEMORY_REPO_ID": self.repo_id,
        }
        env = ", ".join(
            f'{key} = "{self._toml_string(value)}"' for key, value in env_items.items()
        )
        return (
            f"# BEGIN {CODEX_MARKER}\n"
            "[mcp_servers.llm-memory]\n"
            'command = "llm-memory-mcp"\n'
            "args = []\n"
            f'cwd = "{self._toml_string(self.project_root)}"\n'
            f"env = {{ {env} }}\n"
            f"# END {CODEX_MARKER}\n"
        )

    def _install_agents_instructions(self) -> bool:
        instructions = f"""# AGENTS.md

{AGENTS_MARKER} START

{self._workflow_instructions()}

## LLM Memory Context

Run `llm-memory hooks update codex` to populate current memory context.

{AGENTS_MARKER} END
"""
        if self.dry_run:
            return True

        if not self.context_file.exists():
            self._ensure_directory(self.context_file)
            self.context_file.write_text(instructions, encoding="utf-8")
            return True

        content = self.context_file.read_text(encoding="utf-8")
        if f"{AGENTS_MARKER} START" in content and f"{AGENTS_MARKER} END" in content:
            return True

        with self.context_file.open("a", encoding="utf-8") as f:
            f.write("\n\n" + instructions.replace("# AGENTS.md\n\n", ""))
        return True

    def _workflow_instructions(self) -> str:
        return f"""## Codex Memory Workflow

Use llm-memory as the persistent project memory for this repository.

- Before changing code, run `llm-memory remember --repo {self.repo_id}` or call
  MCP `memory_remember`, then run `llm-memory recall "<task>" --repo {self.repo_id}`
  or call MCP `memory_recall`.
- For file-specific risk, call MCP `memory_file_context` or run
  `llm-memory inject --file <path> --task "<task>"`.
- After meaningful work, record bug fixes, decisions, conventions, fragile areas,
  and follow-up goals with `llm-memory record`, `llm-memory decision`,
  `llm-memory learn`, or MCP `memory_after_work`.
- Keep memory scoped to repo `{self.repo_id}` unless intentionally recording
  cross-project knowledge.
- Do not print secrets, prompts, responses, API keys, or unrelated repo/team memory.
"""

    def _install_codex_config(self) -> bool:
        block = self.config_block()
        if self.dry_run:
            return True

        self._ensure_directory(self.config_path)
        content = self.config_path.read_text(encoding="utf-8") if self.config_path.exists() else ""
        new_content = self._replace_marked_block(content, block)
        if new_content is None:
            return False

        self.config_path.write_text(new_content, encoding="utf-8")
        return True

    def _remove_agents_instructions(self) -> bool:
        if self.dry_run or not self.context_file.exists():
            return True

        content = self.context_file.read_text(encoding="utf-8")
        new_content = self._remove_marked_section(
            content, f"{AGENTS_MARKER} START", f"{AGENTS_MARKER} END"
        )
        if new_content == content:
            return True

        self.context_file.write_text(new_content.strip() + "\n", encoding="utf-8")
        return True

    def _remove_codex_config(self) -> bool:
        if self.dry_run or not self.config_path.exists():
            return True

        content = self.config_path.read_text(encoding="utf-8")
        new_content = self._remove_marked_section(
            content, f"# BEGIN {CODEX_MARKER}", f"# END {CODEX_MARKER}"
        )
        self.config_path.write_text(
            new_content.strip() + ("\n" if new_content.strip() else ""), encoding="utf-8"
        )
        return True

    def _replace_agents_block(self, generated: str) -> bool:
        if self.dry_run:
            return True

        content = self.context_file.read_text(encoding="utf-8")
        start_marker = f"{AGENTS_MARKER} START"
        end_marker = f"{AGENTS_MARKER} END"
        if start_marker not in content or end_marker not in content:
            return False

        before = content.split(start_marker)[0]
        after = content.split(end_marker)[1]
        self.context_file.write_text(
            f"{before}{start_marker}\n\n{generated}\n{end_marker}{after}", encoding="utf-8"
        )
        return True

    def _replace_marked_block(self, content: str, block: str) -> str | None:
        begin = f"# BEGIN {CODEX_MARKER}"
        end = f"# END {CODEX_MARKER}"
        if begin in content and end in content:
            before = content.split(begin)[0]
            after = content.split(end, 1)[1]
            return f"{before}{block}{after.lstrip()}"

        unmanaged_table = "[mcp_servers.llm-memory]" in content
        if unmanaged_table:
            return None

        separator = "" if not content or content.endswith("\n") else "\n"
        return f"{content}{separator}\n{block}" if content else block

    def _remove_marked_section(self, content: str, begin: str, end: str) -> str:
        if begin not in content or end not in content:
            return content

        before = content.split(begin)[0]
        after = content.split(end, 1)[1]
        return before + after

    def _toml_string(self, value: object) -> str:
        return str(value).replace("\\", "\\\\").replace('"', '\\"')
